wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
architecture:
  desc: null
  value: ViG with self Attention
dataset:
  desc: null
  value: CIFAR-100
epochs:
  desc: null
  value: 1000
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.15.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1694691501.915966
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 63
      2:
      - 1
      - 41
      - 49
      - 55
      - 63
      3:
      - 13
      - 16
      - 23
      4: 3.11.5
      5: 0.15.10
      8:
      - 5
